spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=practice1
    username: sa
    password: Password.1
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update